apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: floci-data
  namespace: apps-ns
  labels:
    app: floci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
